<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>schelp</string>
	</array>
	<key>name</key>
	<string>Supercollider Help</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>argument</string>
			<key>match</key>
			<string>argument::</string>
			<key>name</key>
			<string>entity.other.attribute-name</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>tags</string>
			<key>match</key>
			<string>^(.+)::</string>
			<key>name</key>
			<string>entity.name.tag</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(link)::</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.raw</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>link</string>
			<key>end</key>
			<string>(::)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.raw</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.underline.link</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>.+</string>
					<key>name</key>
					<string>markup.underline.link</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(code::)</string>
			<key>beginCaptures</key>
			<dict>
			</dict>
			<key>contentName</key>
			<string>embedded sc code</string>
			<key>end</key>
			<string>(::)</string>
			<key>endCaptures</key>
			<dict>
			</dict>
			<key>name</key>
			<string>source.supercollider.embedded.schelp</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.supercollider</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.schelp</string>
	<key>uuid</key>
	<string>7cd51487-611b-46cb-b2fd-3c768e03ea11</string>
</dict>
</plist>
